# Generated by Django 3.1.5 on 2021-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210126_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='supports GitHub-flavoured Markdown, see markdownguide.org/cheat-sheet. Not all Markdown elements (headings, horizontal line, tables) will render correctly, so stick to Discord-supported formatting please :)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY - e.g assignment due date/event date. Can be left blank. (Google Calendar and TYSK App only)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='important',
            field=models.BooleanField(help_text='this will produce an @everyone ping on Discord and move a post to the Important channel on TYSK App'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(help_text='e.g Blue Gym, W301, Sydney Olympic Park (Google Calendar only)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='e.g English Extension 1, Athletics Carnival', max_length=2000),
        ),
    ]
