# Generated by Django 3.1.5 on 2021-01-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210130_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='push_to_gcal',
            field=models.BooleanField(default=False, help_text='do you want to push this announcement to TYSK SubCal as well?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, help_text='e.g Blue Gym, W301, Sydney Olympic Park (Google Calendar only)', max_length=2000),
        ),
    ]
