# Generated by Django 3.1.5 on 2021-06-30 08:27

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_postfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to=board.models.Post.file_path),
        ),
    ]
